### ISSUE TITLE
New ESP32-C3 chip initialization during production using USB Serial/JTAG interface

### ISSUE THREAD

**Issue by JBHunterI** [espressif/esp32c3-direct-boot-example#10]
I've been using the ESP32-C3 DevKitM-1's ability to be debugged through its USB Serial/JTAG interface (USB_D+/-) rather than its 4-wire JTAG interface (TMS/TCK/TDI/TDO) since it came with application firmware already programmed into its Flash that presumably initializes the USB Serial/JTAG interface. That's working well for me, even in the worst case of having to hold the BOOT button on the kit when releasing the RST button to recover debug control from a non-booting app by re-programming Flash with a booting app.

I'm concerned about the USB Serial/JTAG interface's viability for when move to a production phase. What happens when we receive  ESP32-C3-MINI-1 modules on tapes/reels & solder them on our custom boards? Will these modules also have a application firmware, or at least a second stage bootloader (if that's all that's needed), to initialize the chip's USB Serial/JTAG interface into a functional state, or will the module's Flash memory be completely blank/empty/garbage? If there's not enough firmware on the chip right off the tape/reel, would this "direct boot" feature be necessary & sufficient to program our production firmware image into Flash memory, or will the 4-wire JTAG interface be required to program our app image during our custom board's production phase?

**Comment by JBHunterI** [comment]
The [Bootloader](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/bootloader.html#bootloader) section of the ESP-IDF Programming Guide says:

    The ESP-IDF Software Bootloader performs the following functions:
        1. Minimal initial configuration of internal modules;

Does the "initial configuration of internal modules" by this (second stage) Bootloader include that of the USB Serial/JTAG interface?

**Comment by JBHunterI** [comment]
Anyone?

**Comment by erhankur** [comment]
Hi @JBHunterI You can establish a connection through usb_serial_jtag and load applications from OpenOCD, even if the chip is powered up without any contents in the flash (such as the 2nd stage bootloader, partition.bin, and app.bin).
