### ISSUE TITLE
Is the direct boot example is considered as the First Stage Bootloader for the ESP32-C3?

### ISSUE THREAD

**Issue by afifahsyukri** [espressif/esp32c3-direct-boot-example#11]
Hi, I just want a clarification whether this example is the same for first stage bootloader of the ESP32 as mentioned in the API document. If yes, is it possible for the bootloader to be overwritten if I want to flash it into my ESP32C3-Mini-V1 chip? Any guidance would be very helpful. 

Thank you in advance

**Comment by igrr** [comment]
Hi @afifahsyukri, the first stage bootloader of ESP32-C3 (and all other ESP32 series of chips) is in ROM and can not be overwritten. That ROM bootloader is capable of booting applications from Flash. The application loaded from Flash can be: the second stage bootloader, as in IDF; or a standalone application, as in this example.
Hope this helps.

**Comment by afifahsyukri** [comment]
May I know how may I access the first-stage bootloader source code for
ESP32-C3? Any guidance or help would be greatly appreciated.

Regards,
Afifah.

**Comment by igrr** [comment]
ROM bootloader code of the existing chips is not open source, I'm afraid. We do provide ELF files for debugging, in case that helps: https://github.com/espressif/esp-rom-elfs/releases
