### ISSUE TITLE
【Startup Flow】How to load the 2th Boot to RAM at the startup stage

### ISSUE THREAD

**Issue by xiaolongba** [espressif/esp32c3-direct-boot-example#2]
Hi espressif experts,

Recently, I have been writing one tutorial about startup flow which is from power on to app_main() function. I have encountered several doubts about startup even if there is one doc about introducing this [application flow](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/startup.html) online, but more details I would like to know can not be found from that, so I reported them here, could you give me a hand, the details as below:

1. As we all know, the 1st boot has been called from ROM first when power on and then load the 2th boot from spi flash and its offset is 0x00. however, the detailed information can not be disclosed from the official doc, so  I wonder the over process which is loading the 2th boot from flash to ROM.  could you give me more information about it?

1. Based on the information I consulted online, the 1st boot may check the first 24bytes of 2th boot file from spi flash, but I dont know which ways ROM used to check this header information, SPI access or Cache MMU?

2. after obtaining the header information, how to load the remaining content to RAM? SPI access or Cache MMU?
3.  if it is possible, could you show me how to map the external flash to the internal address space? that will be better if you can give me an example.

at last, the reason why I research it deeply is to show this process for all freshmen and it can push the esp32-c3 more efficiently and reduce the support loading in the future indirectly.

thanks in advance. waiting for your news.

**Comment by igrr** [comment]
Hi @xiaolongba,

> so I wonder the over process which is loading the 2th boot from flash to ROM. could you give me more information about it?

The ROM bootloader checks the boot mode, set by the strapping pins. If the boot mode is "flash boot", it proceeds to load the application from flash. (Note that I use the word "application" because the ROM bootloader doesn't care if it is loading the 2nd stage bootloader or something else.)

First, ROM bootloader loads the application image header and checks if what it has loaded looks like a valid header. If yes, it proceeds to iterate over the image segments, loading each of them into RAM. The format of headers and segments is described in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/app_image_format.html#app-image-format. While segments are loaded, SHA hash of the image is also being calculated. Once the segments have been loaded, if SHA hash appended to the binary image matches the calculated hash, the bootloader jumps to the entry point of the application.

When Secure Boot is enabled, the process gets a bit more complex to prevent ToC-ToU attacks, but the essence is the same.

> Based on the information I consulted online, the 1st boot may check the first 24bytes of 2th boot file from spi flash, but I dont know which ways ROM used to check this header information, SPI access or Cache MMU?

> after obtaining the header information, how to load the remaining content to RAM? SPI access or Cache MMU?

In all cases, ROM bootloader uses Cache to read the binary image. This is not done for any performance related reasons, only because reading via Cache is the only way to use transparent AES-XTS decryption if the Flash Encryption feature is enabled.

> if it is possible, could you show me how to map the external flash to the internal address space? that will be better if you can give me an example.

Do you want to do this in some simple bare-metal application or in ESP-IDF? If in ESP-IDF, you can call `spi_flash_mmap` function. I don't have an example of how to do this in a bare-metal application, I'm sorry. If you need this to prepare some tutorial or educational material, is that just to illustrate the concept of Cache memory and XIP, or for some more practical reason?

**Comment by xiaolongba** [comment]
wow... @igrr millions of thanks for your quick response.

> First, ROM bootloader loads the application image header and checks if what it has loaded looks like a valid header. If yes, it proceeds to iterate over the image segments, loading each of them into RAM. The format of headers and segments is described in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/app_image_format.html#app-image-format. While segments are loaded, SHA hash of the image is also being calculated. Once the segments have been loaded, if SHA hash appended to the binary image matches the calculated hash, the bootloader jumps to the entry point of the application.

very clear. I have checked and understood this before

> In all cases, ROM bootloader uses Cache to read the binary image. This is not done for any performance related reasons, only because reading via Cache is the only way to use transparent AES-XTS decryption if the Flash Encryption feature is enabled.

as you said above, if it is the same if the secured boot is disabled? what I mean is no matter secured boot is enabled or not, ROM boot has to read the binary image via Cache, am I rignt?

>  If you need this to prepare some tutorial or educational material, is that just to illustrate the concept of Cache memory and XIP, or for some more practical reason?

exactly, My dear bro, my main purpose is for educational materials. I am preparing to write series tutorials about ESP32-C3. I have finished serial tutorials about Nordic 52840 mesh before. for this, if it is possible to explain more for me?

thanks again bro.

**Comment by igrr** [comment]
> no matter secured boot is enabled or not, ROM boot has to read the binary image via Cache, am I rignt?

That is correct.

Regarding ESP32-C3 tutorials, that's great to hear! I'm curious what your target audience is. If the audience will be IoT developers and application developers, it seems that telling them about ESP-IDF functions `spi_flash_mmap` / `esp_partition_mmap` would be the most appropriate. Or, if you would like to show how to use ESP32-C3 with [NuttX RTOS](https://github.com/apache/incubator-nuttx), then `esp32_mmap` function could be used. My thinking is that IoT and application developers will likely want to have connectivity in their products, so they would have to use some framework like ESP-IDF or NuttX; with that, it is not much benefit to learn writing bare-metal applications.

On the other hand, if your audience are developers who would write bare-metal applications or port their own operating systems to ESP32-C3, then indeed demonstrating the usage of low level features such as Cache MMU would make sense.

ESP32-C3 ROM code provides a few functions which can be used to set up the Cache MMU. If you need to map Flash memory to the instruction address range, you can use Cache_Ibus_MMU_Set; for mapping to data address range, use Cache_Dbus_MMU_Set. The functions are declared [here](https://github.com/espressif/esp-idf/blob/1d7068e4be430edd92bb63f2d922036dcf5c3cc1/components/esp_rom/include/esp32c3/rom/cache.h#L192-L246), there is some information in the header file about the purpose of each argument.
As I said unfortunately I don't have an example which does something useful by calling these functions, but hopefully the header file gives you some hint. You can also look at how these functions are used in `set_cache_and_start_app` function of the 2nd stage bootloader in IDF: https://github.com/espressif/esp-idf/blob/1d7068e4be430edd92bb63f2d922036dcf5c3cc1/components/bootloader_support/src/bootloader_utility.c.

**Comment by xiaolongba** [comment]
@igrr 

Big thanks, bro. actually you gave me lots of useful information already, for instance,

> ESP32-C3 ROM code provides a few functions which can be used to set up the Cache MMU. If you need to map Flash memory to the instruction address range, you can use Cache_Ibus_MMU_Set; for mapping to data address range, use Cache_Dbus_MMU_Set. The functions are declared here, there is some information in the header file about the purpose of each argument.
As I said unfortunately I don't have an example which does something useful by calling these functions, but hopefully the header file gives you some hint. You can also look at how these functions are used in set_cache_and_start_app function of the 2nd stage bootloader in IDF: https://github.com/espressif/esp-idf/blob/1d7068e4be430edd92bb63f2d922036dcf5c3cc1/components/bootloader_support/src/bootloader_utility.c.


regarding my target audience, actually, I am not sure who are they. some of them are students or IoT developers. based on my previous experience, most of them are students. but maybe there are some IoT developers who are interested in it. also, I agreed with your opinions about some guys who want to have connectivity in their products. this is also one part of my tutorials, show them how to play the esp32-c3 more easily. in terms of understanding, especially me. I have to understand more than them, and then can explain what happened when encountering some issues. For me, calling the API functions is too easy, that is not my purpose, instead, my aim is to teach them how to play with ESP32-C3 more easily and understand more basic knowledge, rather than how to call the API. and then for espressif, the loading from customers will become lower and lower along more and more guys understand more and more.

at last, I will feedback to you after checking the information you mentioned above and understood already. also I will share with you here an example for illustrating the relationship between Cache and the external flash. but it will take me some time, so pls wait and see.

last and last, the 2nd boot loads the app image and partition table to RAM through Cache MMU as well?


thanks bro.

**Comment by igrr** [comment]
> last and last, the 2nd boot loads the app image and partition table to RAM through Cache MMU as well?

Yes, it uses Cache as well!

2nd stage bootloader works in a similar way to the ROM bootloader, with a bit of extra complexity related to memory-mapped sections in the binary. A typical application consists of a few sections that are loaded into RAM (typically .data, .iram.text) and some sections which stay in Flash and are accessed at run time via Cache (.rodata, .text). The 2nd stage bootloader can load the former into RAM, and can then configure Cache to map the latter into the CPU address space.

I also agree with your point that having deeper understanding of the system generally helps developers, even if they later work at higher level only. It's nice to see you preparing this course and I'm looking forward to see the results!

If you have other questions, feel free to open a topic at esp32.com or an issue in one of our repositories.
