### ISSUE TITLE
Overlapping sections

### ISSUE THREAD

**Issue by AlexManoJAM** [espressif/esp32c3-direct-boot-example#4]
Hi, I was trying a simple code to write to an gpio and after building it I got an overlapping error. The error only appears when I take out the printf() function so I think it somehow affects the layout of memory for the program. The error I got is overlapping between .data and .header LMA sections and between .text.entry and .data LMA sections as one can see below:
![image](https://user-images.githubusercontent.com/35406517/145828726-cf020b88-78b0-4a3c-9e19-6ebedafd0897.png)
After studying the common.ld linker script I found that the most probable reason for why this is happening is because the location counter has to point backwards for some sections. For instance .entry.text section addressed to 0x42000008 is declared earlier than .data addressed to 0x3C000000. According to section 3.10.5 "The Location Counter" from linker script documentation: "The location counter may not be moved backwards inside an output section, and may not be moved backwards outside of an output section if so doing creates areas with overlapping LMAs"
Do you think that the way sections are structured  on common.ld file could be the problem, or it might be something else that is causing the problem?

**Comment by igrr** [comment]
@AlexManoJAM do you think you could push a branch with the code to reproduce this issue somewhere?

**Comment by AlexManoJAM** [comment]
Of course, I created a fork and put a hello_world.c file in it.

**Comment by igrr** [comment]
Thank you, I was able to reproduce the issue. Please try the latest `main` branch — https://github.com/espressif/esp32c3-direct-boot-example/commit/91d08fcb4bf232748943e0d04da851b1110316fb should fix it.

**Comment by AlexManoJAM** [comment]
Thank you for the fast update, with the latest linker script the overlapping issue did go away. Did you try to flash the binary file produced by the build? I'm not able to flash it so I think another problem came out with the new linker. This is what I got now:
![image](https://user-images.githubusercontent.com/35406517/145974372-ee816ce5-9859-4ca5-9ae3-df26c4fc3a8c.png)

**Comment by igrr** [comment]
My bad, I should have checked this before pushing! I'll commit the fix and add some CI check soon.

**Comment by igrr** [comment]
@AlexManoJAM Could you please try https://github.com/espressif/esp32c3-direct-boot-example/pull/5? (this time i have verified it on the real chip)

**Comment by AlexManoJAM** [comment]
I have tried it, but unfortunately, didn´t work.  The overlapping issue keeps persisting but at least Cmake is showing more details.
![image](https://user-images.githubusercontent.com/35406517/146006553-e4b855b2-c7bc-41d0-a1ec-f6b1fb648253.png)

**Comment by Jimmy2027** [comment]
Hi, I'm getting the same error with my toolchain when building the blink example:
```
cmake --build build                                                                                                                                                                                                                       main
[10/12] Linking C executable blink
FAILED: blink
: && /usr/bin/riscv32-unknown-elf-gcc -march=rv32imc_zicsr -mabi=ilp32 -march=rv32imc_zicsr -mabi=ilp32 --specs=nano.specs --specs=nosys.specs   -g -T /home/hendrik/projects/riscv_hello_world/esp32c3-direct-boot-example/examples/blink/build/_deps/esp-hal-components-src/components/soc/esp32c3/ld/esp32c3.peripherals.ld CMakeFiles/blink.dir/blink.c.obj -o blink  common/libcommon.a  hal/libhal.a  -T  /home/hendrik/projects/riscv_hello_world/esp32c3-direct-boot-example/ld/esp32c3/memory.ld  -T  /home/hendrik/projects/riscv_hello_world/esp32c3-direct-boot-example/ld/esp32c3/common.ld  -T  /home/hendrik/projects/riscv_hello_world/esp32c3-direct-boot-example/ld/esp32c3/romfuncs.ld  -Wl,--Map=/home/hendrik/projects/riscv_hello_world/esp32c3-direct-boot-example/examples/blink/build/blink.map  -nostartfiles && :
/usr/libexec/gcc/riscv32-unknown-elf/ld: /usr/lib/gcc/riscv32-unknown-elf/14/../../../../riscv32-unknown-elf/lib/rv32im/ilp32/libg_nano.a(libc_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0x20): warning: _close is not implemented and will always fail
/usr/libexec/gcc/riscv32-unknown-elf/ld: /usr/lib/gcc/riscv32-unknown-elf/14/../../../../riscv32-unknown-elf/lib/rv32im/ilp32/libg_nano.a(libc_a-signalr.o): in function `_getpid_r':
signalr.c:(.text._getpid_r+0x0): warning: _getpid is not implemented and will always fail
/usr/libexec/gcc/riscv32-unknown-elf/ld: /usr/lib/gcc/riscv32-unknown-elf/14/../../../../riscv32-unknown-elf/lib/rv32im/ilp32/libg_nano.a(libc_a-signalr.o): in function `_kill_r':
signalr.c:(.text._kill_r+0x24): warning: _kill is not implemented and will always fail
/usr/libexec/gcc/riscv32-unknown-elf/ld: /usr/lib/gcc/riscv32-unknown-elf/14/../../../../riscv32-unknown-elf/lib/rv32im/ilp32/libg_nano.a(libc_a-lseekr.o): in function `_lseek_r':
lseekr.c:(.text._lseek_r+0x28): warning: _lseek is not implemented and will always fail
/usr/libexec/gcc/riscv32-unknown-elf/ld: /usr/lib/gcc/riscv32-unknown-elf/14/../../../../riscv32-unknown-elf/lib/rv32im/ilp32/libg_nano.a(libc_a-readr.o): in function `_read_r':
readr.c:(.text._read_r+0x28): warning: _read is not implemented and will always fail
/usr/libexec/gcc/riscv32-unknown-elf/ld: section .data LMA [00000000,00000067] overlaps section .header LMA [00000000,00000007]
/usr/libexec/gcc/riscv32-unknown-elf/ld: section .text.entry LMA [00000008,0000002b] overlaps section .data LMA [00000000,00000067]
/usr/libexec/gcc/riscv32-unknown-elf/ld: warning: blink has a LOAD segment with RWX permissions
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

The code builds fine when I add a printf. I know that the build works in the CI with the xpack toolchain but I'm still wondering what the issue might be. 
This is the output of `riscv32-unknown-elf-g++ --print-multi-lib`:
```
rv32i/ilp32;@march=rv32i@mabi=ilp32
rv32im/ilp32;@march=rv32im@mabi=ilp32
rv32iac/ilp32;@march=rv32iac@mabi=ilp32
rv32imac/ilp32;@march=rv32imac@mabi=ilp32
rv32imafc/ilp32f;@march=rv32imafc@mabi=ilp32f
rv64imac/lp64;@march=rv64imac@mabi=lp64
rv64imafdc/lp64d;@march=rv64imafdc@mabi=lp64d

```

**Comment by igrr** [comment]
@Jimmy2027 Looking at the linked commit, it seems the issue was related to some stray sections getting placed at the default offset and overlapping other sections. Perhaps your toolchain produces some sections which aren't accounted for in the linker script.

When you get this failure, does the .map file still get created? If yes, you can look at the map file and see which sections and symbols get placed into these overlapping ranges. Or just upload the map file here and I'll take a look.

**Comment by Jimmy2027** [comment]
thanks for your help @igrr ! This is my `blink.map` that gets created with my toolchain: 
[blink.txt](https://github.com/user-attachments/files/17472502/blink.txt)

For some reason the .data section ends up starting at the same place than the .header

**Comment by Jimmy2027** [comment]
@igrr the code does compile when I remove those [magic numbers](https://github.com/espressif/esp32c3-direct-boot-example/blob/bac08da009a120fbca7f6b290d270fd5bf4df819/ld/esp32c3/common.ld#L8) from the linker script. 
Do I understand correctly that those are needed for the bootloader?
