### ISSUE TITLE
[Feature Request]: disable the watchdog

### ISSUE THREAD

**Issue by ivand58** [espressif/esp32c3-direct-boot-example#7]
@igrr Could you please give a hint how disable the watchdogs or how to refresh them in order to have a working system ?

**Comment by igrr** [comment]
Here's the code snippet from OpenOCD project which disables the watchdogs: https://github.com/espressif/openocd-esp32/blob/2804fbf15083fcb08093a9aaf1981a278f8e5f42/tcl/target/esp32c3.cfg#L39
I think these registers are documented in the esp32-c3 technical reference manual, please take a look there as well.

**Comment by ivand58** [comment]
Thanks for the hint, the WD from TG0 was successfully disabled by
` *(volatile unsigned int *)0x6001F048 = 0;`

but something is wrong with the RTC WD  -
`*(volatile unsigned int *)0x60008090 &= ~((1U<<31)|(1U<<12));
`
or even
`*(volatile unsigned int *)0x60008090 = 0;` doesn't work, and when read back, the content of this register is `0x00013214` , which doesn't look correct ?!
the WD feed also doesn't work - `*(volatile unsigned int *)0x600080A4 = 1U<<31;`

Also the unlocking didn't help ...? Maybe the base address is wrong ?

The output now is:
`ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x10 (RTCWDT_RTC_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
`
Therefore the reset comes from the RTC WD ...

**Comment by ivand58** [comment]
Thank you very much! 
the final solution is:
```
void stopwd(void)
{
    // Timer Group 0 & 1 WDTs
    *(volatile unsigned int *)0x6001f064 = 0x50D83AA1;
    *(volatile unsigned int *)0x6001F048 = 0;
    *(volatile unsigned int *)0x60020064 = 0x50D83AA1;
    *(volatile unsigned int *)0x60020048 = 0;
    // RTC WDT
    *(volatile unsigned int *)0x600080a8 = 0x50D83AA1;
    *(volatile unsigned int *)0x60008090 = 0;
    // SWD
    *(volatile unsigned int *)0x600080b0 = 0x8F1D312A;
    *(volatile unsigned int *)0x600080ac = 0x84B00000;
}
```
