### ISSUE TITLE
Debug using direct boot method

### ISSUE THREAD

**Issue by AlexManoJAM** [espressif/esp32c3-direct-boot-example#8]
Hi, sorry to bother you again, Im trying to figure out how to use openOCD and gdb via JTAG.
Im using the openOCD provided by espressif wich contains the esp32c3 specific script files (e.g esp32c3.cfg), from gdb Im using the one provided by xpack toolchain. First of all, i have disabled the freeRTOS support on the openOCD script. I have also disable all the watchdogs including auto-feeding the swd at the app itself since it seems that the openocd script could´nt manage to do it. On the gdbinit file I have set a breakpoint to the main function. Since the app code is supossed to be executed from rom instead of flash I have tryed to change, on the esp32c3.cfg file, the #configure_esp_workarea function but did´nt work. From the gdb terminal what it seems to happen is that the debugger cant access the external memory (0x42000000). I have read that the first thing OpenOCD does is to read the partition table at 0x8000  and uses mapping from the fisrt application found. Since with direct boot its not needed to flash partition table, openOCD reads a partition table related to other project. Do you think the problem could be related to that?
![image](https://user-images.githubusercontent.com/35406517/168583737-5eada819-a0ba-4950-ae8e-dc1d756d297d.png)

**Comment by igrr** [comment]
That's correct, at the moment OpenOCD only knows how to add breakpoints in Flash if it can detect the mappings between flash and the address space. For the time being you can instruct GDB to use hardware breakpoints (`hb` or `thb` commands instead of `b` and `tb`).

You can also add a command to OpenOCD configuration file to treat all GDB breakpoints as hardware ones. Please search OpenOCD [docs for `gdb_breakpoint_override` command](https://openocd.org/doc/html/Server-Configuration.html#gdbbreakpointoverride).

**Comment by AlexManoJAM** [comment]
The breakpoint set in main is indeed of hardware type so I expected that I would be able to halt the cpu on the function main. But when I use continue command on gdb it frezzes the debug section.
![image](https://user-images.githubusercontent.com/35406517/168595796-b4a1756b-e93e-4efe-b9b5-582dd0b71029.png)
If i use ctrl+c it get stuck on 0x4200046a address.
![image](https://user-images.githubusercontent.com/35406517/168596081-ea0f0ced-8a48-47ac-8cb5-8feaf1c0b6da.png)
which according to the .map file is pointing to _exit function of the app 
![image](https://user-images.githubusercontent.com/35406517/168596648-971a4e49-9a4d-4d94-926e-50ee3fd428f4.png)

**Comment by AlexManoJAM** [comment]
I didn't understand if you were saying that this problem could be related to the lack of a proper partition table or not.

**Comment by AlexManoJAM** [comment]
I also find the value of the sp and gp registers interesting
![image](https://user-images.githubusercontent.com/35406517/168608759-f5ff9190-741d-41a0-9cc2-7c3ea56452d8.png)

**Comment by igrr** [comment]
Could you please also post the contents of your gdbinit file?

(By the way, I'd really appreciate if you post logs as text instead of screenshots! Thank you!)

**Comment by AlexManoJAM** [comment]
Of course!

GDBINIT:
```
target extended-remote :3333
set remote hardware-watchpoint-limit 2
mon reset halt
flushregs
set logging on
set logging file nowatchdog.txt
thb main
```

**Comment by AlexManoJAM** [comment]
Hi, any development on the problem?

**Comment by SimaoLeite** [comment]
Hello I was also trying the direct boot method and I couldn't figure out how to use debug using GDB. Would you provide more info in the subject.

**Comment by igrr** [comment]
Have added debugging instructions in https://github.com/espressif/esp32c3-direct-boot-example/commit/d941265661925cb95e8cc965992efe19fba23507.
